version: '3'

services:
  # Wiremock service
  wiremock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "9090:8080"
    volumes:
      # Mount the mappings directory to configure Wiremock
      - ./src/test/resources/mappings:/home/wiremock/mappings
    command:
      - --verbose
      - --global-response-templating

  # Test service using the app's Dockerfile
  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - wiremock
    volumes:
      # Mount source code for development
      - ./src:/app/src
      # Mount the Maven local repository to cache dependencies
      - ~/.m2:/root/.m2